name: Deploy Terraform (Local Exec)

on:
  workflow_dispatch:

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

  BACKEND_RESGRP: demo.misc
  BACKEND_STORAGE_ACCOUNT: bcmisc
  BACKEND_CONTAINER: tfstate

  TF_DIR: ./test-local-exec

  TF_VAR_image: bencuk/nodejs-demoapp
  TF_VAR_prefix: demotf

jobs:
  deploy-terraform:
    runs-on: ubuntu-18.04
    steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.29

    - uses: actions/checkout@v2
      
    - name: Run Terraform
      working-directory: ${{ env.TF_DIR }}    
      run: source $GITHUB_WORKSPACE/scripts/terraform.sh