name: Deploy Terraform (Multi)

on:
  workflow_dispatch:

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

  BACKEND_RESGRP: demo.misc
  BACKEND_STORAGE_ACCOUNT: bcmisc
  BACKEND_CONTAINER: tfstate

jobs:
  # ================================================================================
  # Deploy the base resources, which is a ACR
  # ================================================================================
  deploy-base:
    env:
      TF_DIR: ./01-base-resources
      TF_VAR_prefix: tfbase      
    runs-on: ubuntu-18.04
    # Pass step outputs as job outputs
    outputs:
      acr_name: ${{ steps.tf-output.outputs.acr_name }}
      acr_rg: ${{ steps.tf-output.outputs.acr_rg }}

    steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.29
        terraform_wrapper: false

    - uses: actions/checkout@v2
      
    - name: Run Terraform
      working-directory: ${{ env.TF_DIR }}    
      run: source $GITHUB_WORKSPACE/scripts/terraform.sh

    - name: Capture TF outputs as step outputs
      id: tf-output
      working-directory: ${{ env.TF_DIR }}
      run: |
        echo "::set-output name=acr_name::$(terraform output acr_name)"
        echo "::set-output name=acr_rg::$(terraform output rg_name)"
  
  # ================================================================================
  # Standard Docker image build and push to ACR 
  # ================================================================================
  build-image:   
    needs: deploy-base
    runs-on: ubuntu-18.04       
    env:
      IMAGE: ${{ needs.deploy-base.outputs.acr_name }}.azurecr.io/myapp
      SERVER: ${{ needs.deploy-base.outputs.acr_name }}.azurecr.io

    steps:
    - name: Checkout nodejs-demoapp
      uses: actions/checkout@master
      with:
        repository: benc-uk/nodejs-demoapp

    - name: Docker build myapp
      run: docker build . -f ./Dockerfile -t $IMAGE

    - name: Docker login ${{ env.SERVER }}
      run: docker login -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET $SERVER

    - name: Docker push ${{ env.IMAGE }}
      run: docker push $IMAGE        

  # ================================================================================
  # Deploy the app as ACI pulling from the ACR created in base
  # ================================================================================
  deploy-app:
    needs: [ build-image, deploy-base ]
    env:
      TF_DIR: ./02-aci-app
      TF_VAR_prefix: tfapp
      TF_VAR_image: myapp     
      TF_VAR_acr_name: ${{ needs.deploy-base.outputs.acr_name }}
      TF_VAR_acr_rg: ${{ needs.deploy-base.outputs.acr_rg }}
    runs-on: ubuntu-18.04

    steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.29
        terraform_wrapper: false

    - uses: actions/checkout@v2
      
    - name: Run Terraform
      working-directory: ${{ env.TF_DIR }}    
      run: source $GITHUB_WORKSPACE/scripts/terraform.sh